/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

public class VentanaDeJuego extends javax.swing.JFrame {

    Tablero tablero = new Tablero();

    public VentanaDeJuego() {
        initComponents();
        tablero = Juego.GenerarTablero();
        acomodar();
        ganar.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public String[] getListaPiezas() {
        String[] indices = new String[16];
        int cont = 0;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                indices[cont] = "" + tablero.get(i, j);
                cont++;
            }
        }
        return indices;
    }

    public void acomodar() {
        String[] indices = getListaPiezas();
        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[0] + ".jpg")));
        j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[1] + ".jpg")));
        j3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[2] + ".jpg")));
        j4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[3] + ".jpg")));
        j5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[4] + ".jpg")));
        j6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[5] + ".jpg")));
        j7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[6] + ".jpg")));
        j8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[7] + ".jpg")));
        j9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[8] + ".jpg")));
        j10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[9] + ".jpg")));
        j11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[10] + ".jpg")));
        j12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[11] + ".jpg")));
        j13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[12] + ".jpg")));
        j14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[13] + ".jpg")));
        j15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[14] + ".jpg")));
        j16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/" + indices[15] + ".jpg")));
    }

    public void mover(Coordenada actual) {
        Coordenada nueva = darNuevaPosicion(actual);
        if (nueva != null) {
            tablero.intercambiar(actual, nueva);
        }
        acomodar();
        verificarEstadoJuego();
    }

    private void verificarEstadoJuego() {
        if (WIN() == true) {
            ganar.show();
            reintentar retry = new reintentar();
            this.hide();
            retry.show();
        }
    }

    private Coordenada darNuevaPosicion(Coordenada actual) {
        int x = actual.x;
        int y = actual.y;
        if (x > 0 && tablero.get(x - 1, y) == 16) {
            return new Coordenada(x - 1, y);
        }
        if (x < 3 && tablero.get(x + 1, y) == 16) {
            return new Coordenada(x + 1, y);
        }
        if (y < 3 && tablero.get(x, y + 1) == 16) {
            return new Coordenada(x, y + 1);
        }
        if (y > 0 && tablero.get(x, y - 1) == 16) {
            return new Coordenada(x, y - 1);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ganar = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        j4 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        j3 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        j6 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        j5 = new javax.swing.JLabel();
        p8 = new javax.swing.JPanel();
        j8 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        j7 = new javax.swing.JLabel();
        p12 = new javax.swing.JPanel();
        j12 = new javax.swing.JLabel();
        p9 = new javax.swing.JPanel();
        j9 = new javax.swing.JLabel();
        p10 = new javax.swing.JPanel();
        j10 = new javax.swing.JLabel();
        p11 = new javax.swing.JPanel();
        j11 = new javax.swing.JLabel();
        p14 = new javax.swing.JPanel();
        j14 = new javax.swing.JLabel();
        p15 = new javax.swing.JPanel();
        j15 = new javax.swing.JLabel();
        p13 = new javax.swing.JPanel();
        j13 = new javax.swing.JLabel();
        p16 = new javax.swing.JPanel();
        j16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/max/win.png"))); // NOI18N
        getContentPane().add(ganar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 330));

        p2.setPreferredSize(new java.awt.Dimension(50, 50));

        j2.setText("jLabel1");
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 49, -1, -1));

        p1.setForeground(new java.awt.Color(255, 102, 102));
        p1.setPreferredSize(new java.awt.Dimension(50, 50));

        j1.setText("jLabel1");
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 49, -1, -1));

        p4.setPreferredSize(new java.awt.Dimension(50, 50));

        j4.setText("jLabel1");
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 50, 50, -1));

        p3.setPreferredSize(new java.awt.Dimension(50, 50));

        j3.setText("jLabel1");
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 50, -1, -1));

        p6.setPreferredSize(new java.awt.Dimension(50, 50));

        j6.setText("jLabel1");
        j6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 110, -1, -1));

        p5.setPreferredSize(new java.awt.Dimension(50, 50));

        j5.setText("jLabel1");
        j5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 110, -1, -1));

        p8.setPreferredSize(new java.awt.Dimension(50, 50));

        j8.setText("jLabel1");
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 110, 50, -1));

        p7.setPreferredSize(new java.awt.Dimension(50, 50));

        j7.setText("jLabel1");
        j7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 110, -1, -1));

        p12.setPreferredSize(new java.awt.Dimension(50, 50));

        j12.setText("jLabel1");
        j12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p12Layout = new javax.swing.GroupLayout(p12);
        p12.setLayout(p12Layout);
        p12Layout.setHorizontalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p12Layout.setVerticalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 171, 50, -1));

        p9.setPreferredSize(new java.awt.Dimension(50, 50));

        j9.setText("jLabel1");
        j9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p9Layout = new javax.swing.GroupLayout(p9);
        p9.setLayout(p9Layout);
        p9Layout.setHorizontalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p9Layout.setVerticalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 171, -1, -1));

        p10.setPreferredSize(new java.awt.Dimension(50, 50));

        j10.setText("jLabel1");
        j10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p10Layout = new javax.swing.GroupLayout(p10);
        p10.setLayout(p10Layout);
        p10Layout.setHorizontalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p10Layout.setVerticalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 171, -1, -1));

        p11.setPreferredSize(new java.awt.Dimension(50, 50));

        j11.setText("jLabel1");
        j11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 171, -1, -1));

        p14.setPreferredSize(new java.awt.Dimension(50, 50));

        j14.setText("jLabel1");
        j14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p14Layout = new javax.swing.GroupLayout(p14);
        p14.setLayout(p14Layout);
        p14Layout.setHorizontalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p14Layout.setVerticalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 232, -1, -1));

        p15.setPreferredSize(new java.awt.Dimension(50, 50));

        j15.setText("jLabel1");
        j15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p15Layout = new javax.swing.GroupLayout(p15);
        p15.setLayout(p15Layout);
        p15Layout.setHorizontalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p15Layout.setVerticalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 232, -1, -1));

        p13.setPreferredSize(new java.awt.Dimension(50, 50));

        j13.setText("jLabel1");
        j13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p13Layout = new javax.swing.GroupLayout(p13);
        p13.setLayout(p13Layout);
        p13Layout.setHorizontalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p13Layout.setVerticalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 232, -1, -1));

        p16.setPreferredSize(new java.awt.Dimension(50, 50));

        j16.setText("jLabel1");
        j16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p16Layout = new javax.swing.GroupLayout(p16);
        p16.setLayout(p16Layout);
        p16Layout.setHorizontalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        p16Layout.setVerticalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 232, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/max/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 330, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed
    public boolean WIN() {
        int cont = 1;
        int aux = 0;
        boolean win = false;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                if (cont == tablero.get(i, j)) {
                    aux++;
                }
                cont++;
            }
        }
        if (aux == 16) {
            win = true;
        }
        return win;
    }


    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked
        mover(new Coordenada(0, 0));
    }//GEN-LAST:event_j1MouseClicked

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        mover(new Coordenada(0, 1));
    }//GEN-LAST:event_j2MouseClicked

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        mover(new Coordenada(0, 2));
    }//GEN-LAST:event_j3MouseClicked

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
        mover(new Coordenada(0, 3));
    }//GEN-LAST:event_j4MouseClicked

    private void j5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseClicked
        mover(new Coordenada(1, 0));
    }//GEN-LAST:event_j5MouseClicked

    private void j6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseClicked
        mover(new Coordenada(1, 1));
    }//GEN-LAST:event_j6MouseClicked

    private void j7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseClicked
        mover(new Coordenada(1, 2));
    }//GEN-LAST:event_j7MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
        mover(new Coordenada(1, 3));
    }//GEN-LAST:event_j8MouseClicked

    private void j9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j9MouseClicked
        mover(new Coordenada(2, 0));
    }//GEN-LAST:event_j9MouseClicked

    private void j10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10MouseClicked
        mover(new Coordenada(2, 1));
    }//GEN-LAST:event_j10MouseClicked

    private void j11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j11MouseClicked
        mover(new Coordenada(2, 2));
    }//GEN-LAST:event_j11MouseClicked

    private void j12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j12MouseClicked
        mover(new Coordenada(2, 3));
    }//GEN-LAST:event_j12MouseClicked

    private void j13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j13MouseClicked
        mover(new Coordenada(3, 0));
    }//GEN-LAST:event_j13MouseClicked

    private void j14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j14MouseClicked
        mover(new Coordenada(3, 1));
    }//GEN-LAST:event_j14MouseClicked

    private void j15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j15MouseClicked
        mover(new Coordenada(3, 2));
    }//GEN-LAST:event_j15MouseClicked

    private void j16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j16MouseClicked
        mover(new Coordenada(3, 3));
    }//GEN-LAST:event_j16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ganar;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j13;
    private javax.swing.JLabel j14;
    private javax.swing.JLabel j15;
    private javax.swing.JLabel j16;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p12;
    private javax.swing.JPanel p13;
    private javax.swing.JPanel p14;
    private javax.swing.JPanel p15;
    private javax.swing.JPanel p16;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    // End of variables declaration//GEN-END:variables
}
